# Copyright (c) 2026 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//base/update/updateservice/updateengine.gni")

battery_state_root_path = "$updateengine_root_path/services/firmware/common/battery_state"

battery_state_include = [ "$battery_state_root_path/include" ]
battery_state_src = []

if (defined(global_parts_info) &&
    defined(global_parts_info.powermgr_battery_manager)) {
  battery_state_src += [ "$battery_state_root_path/src/battery_state_utils.cpp" ]
} else {
  battery_state_src += [ "$battery_state_root_path/src/battery_state_utils_fake.cpp" ]
}
